// Comprehensive OSM tag database for PlazaQL LSP autocompletions
// Source: OSM wiki / taginfo — covers ~90% of common usage

export interface TagValueInfo {
  value: string;
  description?: string;
}

export interface TagKeyInfo {
  key: string;
  description: string;
  rank: number;
  values: TagValueInfo[];
  freeform?: boolean;
}

export const OSM_TAG_DATABASE: TagKeyInfo[] = [
  {
    key: "amenity",
    description: "Point of interest type",
    rank: 1,
    values: [
      { value: "cafe" },
      { value: "restaurant" },
      { value: "pharmacy" },
      { value: "hospital" },
      { value: "school" },
      { value: "fuel" },
      { value: "atm" },
      { value: "fire_station" },
      { value: "charging_station" },
      { value: "pub" },
      { value: "bar" },
      { value: "fast_food" },
      { value: "bank" },
      { value: "post_office" },
      { value: "library" },
      { value: "kindergarten" },
      { value: "bench" },
      { value: "parking" },
      { value: "toilets" },
      { value: "drinking_water" },
      { value: "place_of_worship" },
      { value: "police" },
      { value: "cinema" },
      { value: "theatre" },
      { value: "marketplace" },
      { value: "community_centre" },
      { value: "dentist" },
      { value: "doctors" },
      { value: "veterinary" },
      { value: "ice_cream" },
      { value: "biergarten" },
      { value: "nightclub" },
      { value: "car_wash" },
      { value: "car_rental" },
      { value: "bicycle_rental" },
      { value: "bus_station" },
      { value: "taxi" },
      { value: "shelter" },
      { value: "waste_basket" },
      { value: "recycling" },
      { value: "fountain" },
      { value: "clock" },
      { value: "post_box" },
      { value: "bicycle_parking" },
    ],
  },
  {
    key: "shop",
    description: "Type of shop or store",
    rank: 2,
    values: [
      { value: "supermarket" },
      { value: "convenience" },
      { value: "greengrocer" },
      { value: "grocery" },
      { value: "bicycle" },
      { value: "bakery" },
      { value: "butcher" },
      { value: "clothes" },
      { value: "hairdresser" },
      { value: "hardware" },
      { value: "car_repair" },
      { value: "electronics" },
      { value: "florist" },
      { value: "furniture" },
      { value: "mobile_phone" },
      { value: "optician" },
      { value: "shoes" },
      { value: "sports" },
      { value: "books" },
      { value: "beauty" },
      { value: "chemist" },
      { value: "deli" },
      { value: "department_store" },
      { value: "gift" },
      { value: "jewelry" },
      { value: "kiosk" },
      { value: "laundry" },
      { value: "newsagent" },
      { value: "pet" },
      { value: "stationery" },
      { value: "toys" },
      { value: "travel_agency" },
      { value: "variety_store" },
      { value: "alcohol" },
      { value: "car" },
    ],
  },
  {
    key: "tourism",
    description: "Tourism-related feature",
    rank: 3,
    values: [
      { value: "museum" },
      { value: "viewpoint" },
      { value: "attraction" },
      { value: "camp_site" },
      { value: "caravan_site" },
      { value: "hotel" },
      { value: "motel" },
      { value: "hostel" },
      { value: "guest_house" },
      { value: "information" },
      { value: "picnic_site" },
      { value: "artwork" },
      { value: "gallery" },
      { value: "theme_park" },
      { value: "zoo" },
    ],
  },
  {
    key: "leisure",
    description: "Leisure and recreation feature",
    rank: 4,
    values: [
      { value: "park" },
      { value: "playground" },
      { value: "garden" },
      { value: "sports_centre" },
      { value: "swimming_pool" },
      { value: "pitch" },
      { value: "stadium" },
      { value: "golf_course" },
      { value: "nature_reserve" },
      { value: "fitness_centre" },
      { value: "track" },
      { value: "dog_park" },
      { value: "marina" },
      { value: "water_park" },
    ],
  },
  {
    key: "highway",
    description: "Road, path, or highway feature",
    rank: 5,
    values: [
      { value: "bus_stop" },
      { value: "cycleway" },
      { value: "primary" },
      { value: "secondary" },
      { value: "trunk" },
      { value: "motorway" },
      { value: "residential" },
      { value: "footway" },
      { value: "path" },
      { value: "service" },
      { value: "tertiary" },
      { value: "unclassified" },
      { value: "living_street" },
      { value: "pedestrian" },
      { value: "track" },
      { value: "crossing" },
      { value: "traffic_signals" },
      { value: "street_lamp" },
      { value: "speed_camera" },
      { value: "turning_circle" },
      { value: "mini_roundabout" },
      { value: "steps" },
      { value: "bridleway" },
      { value: "motorway_link" },
      { value: "motorway_junction" },
    ],
  },
  {
    key: "building",
    description: "Building type",
    rank: 6,
    values: [
      { value: "yes" },
      { value: "residential" },
      { value: "apartments" },
      { value: "commercial" },
      { value: "industrial" },
      { value: "retail" },
      { value: "church" },
      { value: "school" },
      { value: "hospital" },
      { value: "garage" },
      { value: "house" },
      { value: "office" },
      { value: "warehouse" },
      { value: "hotel" },
      { value: "public" },
      { value: "university" },
      { value: "barn" },
      { value: "cabin" },
      { value: "shed" },
      { value: "terrace" },
      { value: "detached" },
      { value: "semidetached_house" },
    ],
  },
  {
    key: "natural",
    description: "Natural or physical land feature",
    rank: 7,
    values: [
      { value: "coastline" },
      { value: "peak" },
      { value: "water" },
      { value: "tree" },
      { value: "wood" },
      { value: "scrub" },
      { value: "grassland" },
      { value: "wetland" },
      { value: "beach" },
      { value: "cliff" },
      { value: "cave_entrance" },
      { value: "spring" },
      { value: "volcano" },
      { value: "glacier" },
      { value: "bay" },
      { value: "cape" },
      { value: "ridge" },
      { value: "valley" },
    ],
  },
  {
    key: "railway",
    description: "Railway or rail transit feature",
    rank: 8,
    values: [
      { value: "station" },
      { value: "subway_entrance" },
      { value: "tram_stop" },
      { value: "halt" },
      { value: "level_crossing" },
      { value: "platform" },
      { value: "rail" },
      { value: "subway" },
      { value: "tram" },
      { value: "light_rail" },
      { value: "narrow_gauge" },
      { value: "abandoned" },
    ],
  },
  {
    key: "waterway",
    description: "Water feature",
    rank: 9,
    values: [
      { value: "river" },
      { value: "stream" },
      { value: "canal" },
      { value: "ditch" },
      { value: "drain" },
      { value: "dam" },
      { value: "waterfall" },
      { value: "dock" },
      { value: "weir" },
      { value: "lock_gate" },
    ],
  },
  {
    key: "landuse",
    description: "Primary land use",
    rank: 10,
    values: [
      { value: "residential" },
      { value: "commercial" },
      { value: "industrial" },
      { value: "farmland" },
      { value: "forest" },
      { value: "meadow" },
      { value: "orchard" },
      { value: "vineyard" },
      { value: "cemetery" },
      { value: "military" },
      { value: "quarry" },
      { value: "retail" },
      { value: "recreation_ground" },
      { value: "allotments" },
      { value: "reservoir" },
    ],
  },
  {
    key: "cuisine",
    description: "Type of food served",
    rank: 11,
    freeform: true,
    values: [
      { value: "italian" },
      { value: "burger" },
      { value: "pizza" },
      { value: "chinese" },
      { value: "japanese" },
      { value: "mexican" },
      { value: "indian" },
      { value: "thai" },
      { value: "sushi" },
      { value: "american" },
      { value: "french" },
      { value: "german" },
      { value: "greek" },
      { value: "korean" },
      { value: "vietnamese" },
      { value: "turkish" },
      { value: "kebab" },
      { value: "seafood" },
      { value: "steak_house" },
      { value: "vegetarian" },
      { value: "vegan" },
      { value: "coffee_shop" },
      { value: "ice_cream" },
      { value: "regional" },
      { value: "international" },
      { value: "asian" },
      { value: "african" },
      { value: "mediterranean" },
      { value: "arab" },
      { value: "latin_american" },
    ],
  },
  {
    key: "sport",
    description: "Type of sport",
    rank: 12,
    values: [
      { value: "soccer" },
      { value: "tennis" },
      { value: "basketball" },
      { value: "baseball" },
      { value: "swimming" },
      { value: "golf" },
      { value: "volleyball" },
      { value: "cycling" },
      { value: "running" },
      { value: "multi" },
      { value: "table_tennis" },
      { value: "climbing" },
      { value: "skating" },
      { value: "skiing" },
      { value: "gymnastics" },
      { value: "martial_arts" },
      { value: "handball" },
      { value: "cricket" },
      { value: "rugby" },
      { value: "american_football" },
      { value: "hockey" },
      { value: "bowling" },
      { value: "yoga" },
      { value: "fitness" },
      { value: "archery" },
    ],
  },
  {
    key: "religion",
    description: "Religion associated with feature",
    rank: 13,
    values: [
      { value: "christian" },
      { value: "muslim" },
      { value: "jewish" },
      { value: "buddhist" },
      { value: "hindu" },
      { value: "shinto" },
      { value: "sikh" },
      { value: "taoist" },
    ],
  },
  {
    key: "surface",
    description: "Physical surface type",
    rank: 14,
    values: [
      { value: "asphalt" },
      { value: "concrete" },
      { value: "paved" },
      { value: "unpaved" },
      { value: "gravel" },
      { value: "dirt" },
      { value: "grass" },
      { value: "sand" },
      { value: "paving_stones" },
      { value: "cobblestone" },
      { value: "compacted" },
      { value: "fine_gravel" },
      { value: "wood" },
      { value: "metal" },
      { value: "ground" },
    ],
  },
  {
    key: "access",
    description: "Legal access restriction",
    rank: 15,
    values: [
      { value: "yes" },
      { value: "no" },
      { value: "private" },
      { value: "permissive" },
      { value: "customers" },
      { value: "delivery" },
      { value: "designated" },
      { value: "agricultural" },
      { value: "forestry" },
      { value: "destination" },
    ],
  },
  {
    key: "boundary",
    description: "Administrative or other boundary",
    rank: 16,
    values: [
      { value: "administrative" },
      { value: "national_park" },
      { value: "protected_area" },
      { value: "maritime" },
      { value: "political" },
    ],
  },
  {
    key: "place",
    description: "Type of populated place",
    rank: 17,
    values: [
      { value: "city" },
      { value: "town" },
      { value: "village" },
      { value: "hamlet" },
      { value: "suburb" },
      { value: "neighbourhood" },
      { value: "island" },
      { value: "locality" },
      { value: "county" },
      { value: "state" },
      { value: "region" },
      { value: "country" },
    ],
  },
  {
    key: "historic",
    description: "Historical site or monument",
    rank: 18,
    values: [
      { value: "castle" },
      { value: "monument" },
      { value: "memorial" },
      { value: "archaeological_site" },
      { value: "ruins" },
      { value: "battlefield" },
      { value: "fort" },
      { value: "manor" },
      { value: "wayside_cross" },
      { value: "wayside_shrine" },
      { value: "boundary_stone" },
      { value: "building" },
      { value: "city_gate" },
      { value: "tomb" },
      { value: "wreck" },
    ],
  },
  {
    key: "route",
    description: "Type of route relation",
    rank: 19,
    values: [
      { value: "bus" },
      { value: "train" },
      { value: "tram" },
      { value: "subway" },
      { value: "ferry" },
      { value: "bicycle" },
      { value: "hiking" },
      { value: "road" },
      { value: "mtb" },
      { value: "horse" },
      { value: "foot" },
      { value: "canoe" },
    ],
  },
  {
    key: "type",
    description: "Relation type",
    rank: 20,
    values: [
      { value: "multipolygon" },
      { value: "route" },
      { value: "boundary" },
      { value: "restriction" },
      { value: "public_transport" },
      { value: "associatedStreet" },
      { value: "site" },
      { value: "waterway" },
      { value: "enforcement" },
      { value: "destination_sign" },
    ],
  },
  {
    key: "admin_level",
    description: "Administrative level (1=country, 8=municipality)",
    rank: 21,
    values: [
      { value: "1" },
      { value: "2" },
      { value: "3" },
      { value: "4" },
      { value: "5" },
      { value: "6" },
      { value: "7" },
      { value: "8" },
      { value: "9" },
      { value: "10" },
      { value: "11" },
    ],
  },
  {
    key: "wheelchair",
    description: "Wheelchair accessibility",
    rank: 22,
    values: [
      { value: "yes" },
      { value: "no" },
      { value: "limited" },
      { value: "designated" },
    ],
  },
  {
    key: "bicycle",
    description: "Bicycle access",
    rank: 23,
    values: [
      { value: "yes" },
      { value: "no" },
      { value: "designated" },
      { value: "dismount" },
      { value: "use_sidepath" },
      { value: "permissive" },
    ],
  },
  {
    key: "cycleway",
    description: "Type of cycling infrastructure",
    rank: 24,
    values: [
      { value: "lane" },
      { value: "track" },
      { value: "shared_lane" },
      { value: "share_busway" },
      { value: "opposite_lane" },
      { value: "opposite_track" },
      { value: "opposite" },
      { value: "shared" },
    ],
  },
  {
    key: "internet_access",
    description: "Internet access type",
    rank: 25,
    values: [
      { value: "wlan" },
      { value: "yes" },
      { value: "no" },
      { value: "terminal" },
    ],
  },
  {
    key: "outdoor_seating",
    description: "Has outdoor seating",
    rank: 26,
    values: [
      { value: "yes" },
      { value: "no" },
    ],
  },
  {
    key: "organic",
    description: "Sells organic products",
    rank: 27,
    values: [
      { value: "yes" },
      { value: "no" },
      { value: "only" },
    ],
  },
  {
    key: "diet:vegan",
    description: "Vegan food options",
    rank: 28,
    values: [
      { value: "yes" },
      { value: "no" },
      { value: "only" },
    ],
  },
  {
    key: "diet:vegetarian",
    description: "Vegetarian food options",
    rank: 29,
    values: [
      { value: "yes" },
      { value: "no" },
      { value: "only" },
    ],
  },
  {
    key: "drive_through",
    description: "Has drive-through",
    rank: 30,
    values: [
      { value: "yes" },
      { value: "no" },
    ],
  },
  {
    key: "hgv",
    description: "Heavy goods vehicle access",
    rank: 31,
    values: [
      { value: "yes" },
      { value: "no" },
      { value: "designated" },
      { value: "destination" },
      { value: "delivery" },
      { value: "local" },
    ],
  },
  {
    key: "bridge",
    description: "Bridge structure",
    rank: 32,
    values: [
      { value: "yes" },
      { value: "viaduct" },
      { value: "aqueduct" },
      { value: "movable" },
    ],
  },
  {
    key: "tunnel",
    description: "Tunnel structure",
    rank: 33,
    values: [
      { value: "yes" },
      { value: "building_passage" },
      { value: "culvert" },
    ],
  },
  {
    key: "aeroway",
    description: "Aviation-related feature",
    rank: 34,
    values: [
      { value: "aerodrome" },
      { value: "terminal" },
      { value: "helipad" },
      { value: "runway" },
      { value: "taxiway" },
      { value: "apron" },
      { value: "gate" },
      { value: "hangar" },
      { value: "windsock" },
    ],
  },
  {
    key: "maxspeed",
    description: "Maximum speed limit (km/h)",
    rank: 35,
    freeform: true,
    values: [
      { value: "20" },
      { value: "30" },
      { value: "40" },
      { value: "50" },
      { value: "60" },
      { value: "70" },
      { value: "80" },
      { value: "90" },
      { value: "100" },
      { value: "110" },
      { value: "120" },
      { value: "130" },
    ],
  },
  {
    key: "maxheight",
    description: "Maximum vehicle height (meters)",
    rank: 36,
    freeform: true,
    values: [
      { value: "2.5" },
      { value: "3.0" },
      { value: "3.5" },
      { value: "4.0" },
      { value: "4.5" },
    ],
  },
  {
    key: "maxweight",
    description: "Maximum vehicle weight (tonnes)",
    rank: 37,
    freeform: true,
    values: [
      { value: "3.5" },
      { value: "7.5" },
      { value: "12" },
      { value: "16" },
      { value: "40" },
    ],
  },
  {
    key: "name",
    description: "Primary name",
    rank: 38,
    freeform: true,
    values: [],
  },
  {
    key: "brand",
    description: "Brand name",
    rank: 39,
    freeform: true,
    values: [],
  },
  {
    key: "operator",
    description: "Operator or managing organization",
    rank: 40,
    freeform: true,
    values: [],
  },
  {
    key: "ref",
    description: "Reference number or code",
    rank: 41,
    freeform: true,
    values: [],
  },
  {
    key: "addr:street",
    description: "Street name",
    rank: 42,
    freeform: true,
    values: [],
  },
  {
    key: "addr:housenumber",
    description: "House number",
    rank: 43,
    freeform: true,
    values: [],
  },
  {
    key: "addr:city",
    description: "City name",
    rank: 44,
    freeform: true,
    values: [],
  },
  {
    key: "addr:postcode",
    description: "Postal code",
    rank: 45,
    freeform: true,
    values: [],
  },
  {
    key: "addr:country",
    description: "Country code (ISO 3166-1)",
    rank: 46,
    freeform: true,
    values: [],
  },
  {
    key: "phone",
    description: "Phone number",
    rank: 47,
    freeform: true,
    values: [],
  },
  {
    key: "website",
    description: "Website URL",
    rank: 48,
    freeform: true,
    values: [],
  },
  {
    key: "email",
    description: "Email address",
    rank: 49,
    freeform: true,
    values: [],
  },
  {
    key: "opening_hours",
    description: "Opening hours",
    rank: 50,
    freeform: true,
    values: [
      { value: "24/7" },
      { value: "Mo-Fr 08:00-18:00" },
      { value: "Mo-Sa 09:00-20:00" },
    ],
  },
  {
    key: "building:levels",
    description: "Number of building floors",
    rank: 51,
    freeform: true,
    values: [],
  },
  {
    key: "description",
    description: "Description text",
    rank: 52,
    freeform: true,
    values: [],
  },
  {
    key: "wikidata",
    description: "Wikidata item ID (e.g. Q42)",
    rank: 53,
    freeform: true,
    values: [],
  },
  {
    key: "wikipedia",
    description: "Wikipedia article reference",
    rank: 54,
    freeform: true,
    values: [],
  },
];

export const TAG_KEY_MAP: Map<string, TagKeyInfo> = new Map(
  OSM_TAG_DATABASE.map((t) => [t.key, t]),
);
